# Support Bee's development. Uncomment and fill in as funding channels are set up.
# https://docs.github.com/en/repositories/managing-your-repositories-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [bee-ai-labs]
# open_collective: bee-ai
# ko_fi: bee_ai
# custom: ["https://bee-ai.dev/sponsor"]
